unique_ids:
  assets:
    standard-page.html: VS23PXGZHZ7WCUIWHB4GQC3OCA24R3XP
    theme.css: FUMJ27FW557ERBOSAWRRKGXZ3RX5C5HH
  forms:
    Form1: M6R6OKDVSWNGF2WI5AIEYZ3GZTAOR3ZE
  modules: {}
  scripts: {}
  server_modules: {}
